- name: Disable SWAP since kubernetes can't work with swap enabled (1/2)
  shell: |
      swapoff -a
        when: kubernetes_installed is changed

- name: Disable SWAP in fstab since kubernetes can't work with swap enabled (2/2)
  replace:
      path: /etc/fstab
          regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
	      replace: '# \1'
	        when: kubernetes_installed is changed
