# permissions for end users to edit visitor-sites.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: visitor-site-editor-role
rules:
- apiGroups:
  - demo.my.domain
  resources:
  - visitor-sites
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - demo.my.domain
  resources:
  - visitor-sites/status
  verbs:
  - get
