# permissions for end users to view visitor-sites.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: visitor-site-viewer-role
rules:
- apiGroups:
  - demo.my.domain
  resources:
  - visitor-sites
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - demo.my.domain
  resources:
  - visitor-sites/status
  verbs:
  - get
